---
title: "Zhilong's Mainpage"
author: "Zhilong Jia"
date: '`r Sys.Date()`'
output: html_document
---

I am an Assistant Professor in Chinese PLA General Hospital. My research interest is drug repositioning. My ORCID ID is [0000-0003-2370-5073](https://orcid.org/0000-0003-2370-5073).

### Selected papers with Reproducible codes:


* _2020_ [Transcriptome-based drug repositioning for coronavirus disease 2019 (COVID-19)](https://academic.oup.com/femspd/article/78/4/ftaa036/5871823)
   + **Reproducible research**: [code](https://github.com/zhilongjia/COVID-19)
   
* _2020_ [Heightened Innate Immune Responses in the Respiratory Tract of COVID-19 Patients](https://www.sciencedirect.com/science/article/pii/S1931312820302444?via%3Dihub)
   + **Reproducible research (only related to my contributions)**: [code](https://github.com/zhilongjia/nCoV2019)

* _2019_ [Time-Course Transcriptome Analysis for Drug Repositioning in *Fusobacterium nucleatum*-Infected Human Gingival Fibroblasts](https://www.frontiersin.org/articles/10.3389/fcell.2019.00204/full) or [PubMed](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6771468/)
    + **Reproducible research**: [code](https://github.com/zhilongjia/Fn_HGFcell)


* _2019_ [Transcriptional profiling in the livers of rats after hypobaric hypoxia exposure.](https://peerj.com/articles/6499/)
    + **Reproducible research**: [code](https://github.com/zhilongjia/AMS_gut_liver_rat)

* _2016_ [Cogena, a novel tool for co-expressed gene-set enrichment analysis, applied to drug repositioning and drug mode of action discovery](http://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-2737-8)
    + **cogena**: [code](https://github.com/zhilongjia/cogena) or [Bioconductor](http://www.bioconductor.org/packages/devel/bioc/html/cogena.html)
    + **Reproducible research**: [code](https://github.com/zhilongjia/psoriasis)

*  _2015_ [Gene Ranking of RNA-Seq Data via Discriminant Non-Negative Matrix Factorization (DNMF)](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0137782)
    + **DNMF package**: [CRAN](https://cran.r-project.org/web/packages/DNMF/index.html)
    + **Reproducible research**: [code](https://github.com/zhilongjia/geneRanking)


### Meeting with slides:

* [Drug repositioning based on coexpressed gene-set enrichment analysis (cogena)](https://github.com/zhilongjia/slides/blob/master/eurobioc2015_FlashlightII_cogena_ZhilongJia.pdf) at [European Bioconductor Developers' Conference 2015](https://sites.google.com/site/eurobioc2015/)

* [Co-expressed gene-set enrichment analysis for drug repositioning with examples of psoriasis and periodontal diseases](https://github.com/zhilongjia/slides/blob/master/ZhilongJia-BDF20191013-v7.pdf) at [The 4th Big Data Forum for Life and Health Sciences 2019](https://bigd.big.ac.cn/conference/bdf2019)

### Contact:
* [Github](https://github.com/zhilongjia) 
* [Google Scholar](https://scholar.google.com/citations?user=Nrqp1VsAAAAJ&hl=en)
* [LinkedIn](https://uk.linkedin.com/in/zhilongjia)
* [Email](zhilongjia#qq.com)




